### ISSUE TITLE
Error compiling perception_ros

### ISSUE THREAD

**Issue by canglangzhige** [hmz-15/Interactive-Scene-Reconstruction#5]
Error compiling perception_ros：
![image](https://user-images.githubusercontent.com/48430568/178496480-e087a151-5bba-408e-a34c-2bdc431215f2.png)
Some people say that both opencv and pcl define "flann", and the function of opencv is called here instead of pcl. What should I do?

**Comment by canglangzhige** [comment]
pcl_catkin is version 1.10, flann is version 1.9, and flann version 1.10 is not found.

**Comment by canglangzhige** [comment]
In "perception_ros/include/common.h" I found that you have already paid attention to this problem. But why do I still have this problem when building?
![image](https://user-images.githubusercontent.com/48430568/178507839-63109b43-0c18-4fc5-a320-f643ebe07cc3.png)

**Comment by hmz-15** [comment]
I didn't reproduce the error; but I suppose this is due to some package conflicts. Could you try the things below:
1. Use `catkin clean` to clean all the built files and build the single package `perception_ros` with `catkin build perception_ros`
2. If it still doesn't work, check whether you have standalone flann or pcl packages installed system-wise. We expect you have opencv installed; while we provice pcl_catkin as explicit dependency.
